config/routes.rb
BudgetCricket::Application.routes.draw do
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  devise_for :models
  devise_for :users

  resources :posts do
    resources :comments
  end

  resources :budgets do
    resources :expenses
  end

  resources :questions do
    resources :answers
  end

  get "users/sign_in"
  get "welcome/index"
  get "home/index"
  get "budgets/index"
  get "stories/index"
  get "posts/index"
  get "questions/index"
  get "aboutbudget/index"
  get "contactus/index"
  get "aboutus/index"
  get "users/sign_out"

  root to: "welcome#index"

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :answer
  belongs_to :question

  validates :answer, :presence => true, :length => { :minimum => 1 }
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  attr_accessible :description, :name


  validates :name, :presence => true

  has_many :expenses, :dependent => :delete_all


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :commenter, :body
  belongs_to :post
end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible :description, :budget, :title, :cost


  validates :title, :presence => true
  validates :cost, :presence => true

  belongs_to :budget

  def to_s
    ActionController::Base.helpers.number_to_currency(cost)
  end

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :text
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :question

  validates :question, :presence => true

  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  validates_presence_of :email
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_filter :find_question
  before_filter :find_answer, :only => [:show, :edit, :update, :destroy]

  def new
    @answer = @question.answers.build
  end

  def create
    @answer = @question.answers.build(params[:answer])
    if @answer.save
      flash[:notice] = "Answer has been created."
      redirect_to @question
    else
      flash[:alert] = "Answer has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @answer.update_attributes(params[:answer])
      flash[:notice] = "Answer has been updated."
      redirect_to @question
    else
      flash[:alert] = "Answer has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @answer.destroy
    flash[:notice] = "Answer has been deleted."
    redirect_to @question
  end

private
  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = @question.answers.find(params[:id])
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

before_filter :find_budget, :only => [:show, :edit, :update, :destroy]

  def index
    @budgets = Budget.all
  end

  def new
    @budget = Budget.new
  end

  def create
  @budget = Budget.new(params[:budget])
    if @budget.save
      flash[:notice] = "Budget has been created."
      redirect_to @budget
    else
      flash[:alert] = "Budget has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @budget.update_attributes(params[:budget])
      flash[:notice] = "Budget has been updated."
      redirect_to @budget
    else
      flash[:alert] = "Budget has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @budget.destroy
    flash[:notice] = "Budget has been deleted."
    redirect_to budgets_path
  end

private

  def find_budget
    @budget = Budget.find(params[:id])
    rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The budget you were looking" +
                    " for could not be found."
    redirect_to budgets_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:commenter, :body))
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/contactus_controller.rb
class ContactusController < ApplicationController
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  before_filter :find_budget
  before_filter :find_expense, :only => [:show, :edit, :update, :destroy]

  def new
    @expense = @budget.expenses.build
  end

  def create
    @expense = @budget.expenses.build(params[:expense])
    if @expense.save
      flash[:notice] = "Expense has been created."
      redirect_to @budget
    else
      flash[:alert] = "Expense has not been created."
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @expense.update_attributes(params[:expense])
      flash[:notice] = "Expense has been updated."
      redirect_to @budget
    else
      flash[:alert] = "Expense has not been updated."
      render :action => "edit"
    end
  end

  def destroy
    @expense.destroy
    flash[:notice] = "Expense has been deleted."
    redirect_to @budget
  end

private
  def find_budget
    @budget = Budget.find(params[:budget_id])
  end

  def find_expense
    @expense = @budget.expenses.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
  @post = Post.new
end

def create
  @post = Post.new(post_params)
  if @post.save
    redirect_to @post
  else
    render 'new'
  end
end

def edit
  @post = Post.find(params[:id])
end

def update
  @post = Post.find(params[:id])
  if @post.update_attributes(post_params)
    flash[:notice] = "Successfully updated story post."
    redirect_to @post
  else
    render 'edit'
  end
end

def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
end

private
  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Budget Tracker").join(" - ")
      end
    end
  end


end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/answers/_form.html.erb
<%= form_for [@question, @answer] do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :answer %><br>
    <%= f.text_field :answer %>
  </p>
  <%= f.submit %>
<% end %>

app/views/answers/edit.html.erb
<div id="FAQAedit">
  <div id="FAQAeditop">
    <h2>Editing an answer in <%= @question.question %></h2>
  </div>
   <div class="TopLinks">
      |<%= link_to "Wallet", controller: "budgets" %> |
      <%= link_to "Home", controller: "home" %> |
      <%= link_to "Cricket's Stories", controller: "stories"  %> |
    </div>

<%= render "form" %>

    <div class="BottomLinks">
     | <%= link_to "QA Forum", controller: "questions" %> |
      <%= link_to "How to Budget", controller: "aboutbudget" %> |
      <%= link_to "Contact Us", controller: "contactus" %> |
      <%= link_to "About Us", controller: "aboutus" %> |
    </div>
</div>

app/views/answers/new.html.erb
<div id="FAQAnew">
  <div id="FAQAnewtop">
    <h2>Answer this: <%= @question.question %></h2>
  </div>

    <div class="TopLinks">
      |<%= link_to "Wallet", controller: "budgets" %> |
      <%= link_to "Home", controller: "home" %> |
      <%= link_to "Cricket's Stories", controller: "stories"  %> |
    </div>

<%= render "form" %>

    <div class="BottomLinks">
     | <%= link_to "QA Forum", controller: "questions" %> |
      <%= link_to "How to Budget", controller: "aboutbudget" %> |
      <%= link_to "Contact Us", controller: "contactus" %> |
      <%= link_to "About Us", controller: "aboutus" %> |
    </div>
</div>

app/views/answers/show.html.erb
<div id="FAQAshow">
  <div id="FAQAshowtop">
    <h2>Answer to: <%= @question.question %></h2>
  </div>

  <div class="TopLinks">
    |<%= link_to "Wallet", controller: "budgets" %> |
    <%= link_to "Home", controller: "home" %> |
    <%= link_to "Cricket's Stories", controller: "stories"  %> |
  </div>

  <div id='answer'>
    <%= simple_format(@answer.answer) %>
    <%= link_to "Edit Answer", [:edit, @question, @answer] %>
    <%= link_to "Delete Answer", [@question, @answer], :method => :delete,
       :confirm => "Are you sure you want to delete this answer?" %>
  </div>
  <br>

  <%= link_to "Add another answer", new_question_answer_path(@question) %>
  <br>
  <%= link_to "Back to question", question_path(@question) %>
  <br>
  <%= link_to "Back to List of Questions", questions_path %>
  <br>
  <br>

    <div class="BottomLinks">
     | <%= link_to "QA Forum", controller: "questions" %> |
      <%= link_to "How to Budget", controller: "aboutbudget" %> |
      <%= link_to "Contact Us", controller: "contactus" %> |
      <%= link_to "About Us", controller: "aboutus" %> |
    </div>
</div>

app/views/budgets/_form.html.erb
<%= form_for(@budget) do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <%= f.submit %>
<% end %>

app/views/budgets/edit.html.erb
<div id="EditBudget">
  <div id="EditBudgetTop">
    <h2>Edit Budget</h2>
      <div class="TopLinks">
        |<%= link_to "Wallet", controller: "budgets" %> |
        <%= link_to "Home", controller: "home" %> |
        <%= link_to "Cricket's Stories", controller: "stories"  %> |
      </div>
  </div>

<%= render "form" %>

    <div class="BottomLinks">
     | <%= link_to "QA Forum", controller: "questions" %> |
      <%= link_to "How to Budget", controller: "aboutbudget" %> |
      <%= link_to "Contact Us", controller: "contactus" %> |
      <%= link_to "About Us", controller: "aboutus" %> |
    </div>
    <br>
</div>

app/views/budgets/index.html.erb
<div id="wallet">
  <div id="wallettop">
    <h1>Budget Cricket's Wallet</h2>
    <h3>Add your budgets and track expenses!</h3>
  </div>

  <div class="TopLinks">
        |<%= link_to "Wallet", controller: "budgets" %> |
      <%= link_to "Home", controller: "home" %> |
      <%= link_to "Cricket's Stories", controller: "stories"  %> |
  </div>

    <ul>
      <% @budgets.each do |budget| %>
        <li><%= link_to budget.name, budget %></li>
      <% end %>
    </ul>

<%= link_to "New Budget", new_budget_path %>

<br>
    <div class="BottomLinks">
     | <%= link_to "QA Forum", controller: "questions" %> |
      <%= link_to "How to Budget", controller: "aboutbudget" %> |
      <%= link_to "Contact Us", controller: "contactus" %> |
      <%= link_to "About Us", controller: "aboutus" %> |
    </div>
<br>
</div>

app/views/budgets/new.html.erb
<div id="NewBudget">
  <div id="NewBudgetTop">
  <h2>New Budget</h2>
    <div class="TopLinks">
        |<%= link_to "Wallet", controller: "budgets" %> |
        <%= link_to "Home", controller: "home" %> |
        <%= link_to "Cricket's Stories", controller: "stories"  %> |
    </div>
  </div>

<%= render "form" %>

<br>
    <div class="BottomLinks">
     | <%= link_to "QA Forum", controller: "questions" %> |
      <%= link_to "How to Budget", controller: "aboutbudget" %> |
      <%= link_to "Contact Us", controller: "contactus" %> |
      <%= link_to "About Us", controller: "aboutus" %> |
    </div>
    <br>
</div>

app/views/budgets/show.html.erb
<div id="budgetshow">
  <div id="showtop">
    <% title(@budget.name, "Budgets") %>
    <h1><%= @budget.name %></h1>

    <div class="TopLinks">
      |<%= link_to "Wallet", controller: "budgets" %> |
      <%= link_to "Home", controller: "home" %> |
      <%= link_to "Cricket's Stories", controller: "stories"  %> |
    </div>
  </div>

    <p>Description: <%= @budget.description %> </p>
    <br>

  <table>
    <thead>
      <th>Title</th>
      <th>Amount</th>
    </thead>
    <tbody>
      <% @budget.expenses.each do |expense| %>
      <tr id='expense'>
        <td>
          <%= link_to expense.title, [@budget, expense] %>
        </td>
        <td>
          <%= expense %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <br>
  <br>

    ~<%= link_to "Edit Budget", edit_budget_path(@budget) %>~
    ~<%= link_to "Delete Budget", budget_path(@budget),
          :method => :delete,
          :confirm => "Are you sure you want to delete this budget?" %>~
    ~<%= link_to "New Expense", new_budget_expense_path(@budget) %>~
    ~<%= link_to "Back to Budgets", budgets_url %>~
    <br>
    <div class="BottomLinks">
     | <%= link_to "QA Forum", controller: "questions" %> |
      <%= link_to "How to Budget", controller: "aboutbudget" %> |
      <%= link_to "Contact Us", controller: "contactus" %> |
      <%= link_to "About Us", controller: "aboutus" %> |
    </div>
  <br>
</div>